-- Supabase Employee Table Schema
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/ljqcepgtyzbggezqlxdd/sql)

CREATE TABLE IF NOT EXISTS public.employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  department TEXT NOT NULL,
  role TEXT NOT NULL,
  salary NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.employee ENABLE ROW LEVEL SECURITY;

-- Allow read and write access for authenticated & service keys / API keys
CREATE POLICY "Allow public access for employee table" ON public.employee
  FOR ALL USING (true) WITH CHECK (true);

-- Insert sample initial seed data if table is empty
INSERT INTO public.employee (name, username, email, password, department, role, salary)
VALUES 
  ('Alex Johnson', 'alexj', 'alex.johnson@example.com', 'password123', 'Engineering', 'Senior Developer', 95000),
  ('Sarah Connor', 'sarahc', 'sarah.connor@example.com', 'password123', 'Product', 'Product Manager', 105000),
  ('Michael Scott', 'mscott', 'michael.scott@example.com', 'password123', 'Sales', 'Regional Manager', 75000),
  ('Emily Davis', 'emilyd', 'emily.davis@example.com', 'password123', 'Design', 'Lead UI/UX Designer', 88000),
  ('David Miller', 'dmiller', 'david.miller@example.com', 'password123', 'HR', 'HR Specialist', 62000)
ON CONFLICT (email) DO NOTHING;
