import { useState, useEffect, useMemo } from "react";
import { API_BASE_URL } from "../api";

const SQL_SCHEMA_SNIPPET = `CREATE TABLE IF NOT EXISTS public.employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  department TEXT NOT NULL,
  role TEXT NOT NULL,
  salary NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.employee ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access for employee table" ON public.employee
  FOR ALL USING (true) WITH CHECK (true);`;

const DEPARTMENTS = ["All", "Engineering", "Product", "Sales", "Design", "HR"];

const Employees = () => {
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showSql, setShowSql] = useState(false);

  // Search & Filter
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedDept, setSelectedDept] = useState("All");
  const [viewMode, setViewMode] = useState("table"); // 'table' | 'grid'

  // Modals
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingEmployee, setEditingEmployee] = useState(null);
  const [deleteTarget, setDeleteTarget] = useState(null);

  // Toast
  const [toast, setToast] = useState(null);

  // Form State
  const [formData, setFormData] = useState({
    name: "",
    username: "",
    email: "",
    password: "",
    department: "Engineering",
    role: "",
    salary: "",
  });

  const showToastMsg = (message, type = "success") => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  };

  const loadEmployeeData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`${API_BASE_URL}`);
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.message || "Failed to load employee records.");
      }
      setEmployees(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("API Fetch Error:", err);
      setError(err.message || "Could not connect to employee API.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadEmployeeData();
  }, []);

  const handleOpenAddModal = () => {
    setEditingEmployee(null);
    setFormData({
      name: "",
      username: "",
      email: "",
      password: "",
      department: "Engineering",
      role: "",
      salary: "",
    });
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (emp) => {
    setEditingEmployee(emp);
    setFormData({
      name: emp.name || "",
      username: emp.username || "",
      email: emp.email || "",
      password: emp.password || "",
      department: emp.department || "Engineering",
      role: emp.role || "",
      salary: emp.salary ? String(emp.salary) : "",
    });
    setIsModalOpen(true);
  };

  const handleSaveEmployee = async (e) => {
    e.preventDefault();
    try {
      const isEdit = !!editingEmployee;
      const url = isEdit ? `${API_BASE_URL}/${editingEmployee.id}` : `${API_BASE_URL}`;
      const method = isEdit ? "PUT" : "POST";

      const res = await fetch(url, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });

      const result = await res.json();
      if (!res.ok) {
        throw new Error(result.message || "Operation failed.");
      }

      showToastMsg(
        isEdit
          ? "Employee updated successfully!"
          : "New employee created successfully!",
        "success"
      );
      setIsModalOpen(false);
      loadEmployeeData();
    } catch (err) {
      alert(`Error: ${err.message}`);
    }
  };

  const handleDeleteEmployee = async () => {
    if (!deleteTarget) return;
    try {
      const res = await fetch(`${API_BASE_URL}/${deleteTarget.id}`, {
        method: "DELETE",
      });
      const result = await res.json();
      if (!res.ok) {
        throw new Error(result.message || "Failed to delete employee.");
      }

      showToastMsg("Employee deleted successfully", "success");
      setDeleteTarget(null);
      loadEmployeeData();
    } catch (err) {
      alert(`Delete Error: ${err.message}`);
    }
  };

  // Filtered employees
  const filteredEmployees = useMemo(() => {
    return employees.filter((emp) => {
      const matchesSearch =
        (emp.name || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
        (emp.email || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
        (emp.username || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
        (emp.role || "").toLowerCase().includes(searchTerm.toLowerCase()) ||
        (emp.department || "").toLowerCase().includes(searchTerm.toLowerCase());

      const matchesDept =
        selectedDept === "All" ||
        (emp.department || "").toLowerCase() === selectedDept.toLowerCase();

      return matchesSearch && matchesDept;
    });
  }, [employees, searchTerm, selectedDept]);

  // Metric Stats
  const totalEmployees = employees.length;
  const totalSalary = useMemo(
    () => employees.reduce((acc, curr) => acc + (Number(curr.salary) || 0), 0),
    [employees]
  );
  const avgSalary = totalEmployees ? Math.round(totalSalary / totalEmployees) : 0;
  const activeDepts = useMemo(
    () => new Set(employees.map((e) => e.department).filter(Boolean)).size,
    [employees]
  );

  const getInitials = (name = "") => {
    return name
      .split(" ")
      .map((part) => part[0])
      .join("")
      .toUpperCase()
      .slice(0, 2) || "EMP";
  };

  const getBadgeClass = (dept = "") => {
    const d = dept.toLowerCase();
    if (d.includes("engineer") || d.includes("dev")) return "badge-engineering";
    if (d.includes("sales")) return "badge-sales";
    if (d.includes("product")) return "badge-product";
    if (d.includes("design") || d.includes("ui")) return "badge-design";
    if (d.includes("hr") || d.includes("people")) return "badge-hr";
    return "badge-default";
  };

  return (
    <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "24px 20px" }}>
      {/* Toast Notification */}
      {toast && (
        <div
          style={{
            position: "fixed",
            top: "20px",
            right: "20px",
            background: toast.type === "success" ? "#10b981" : "#ef4444",
            color: "#fff",
            padding: "12px 20px",
            borderRadius: "12px",
            boxShadow: "0 10px 25px rgba(0,0,0,0.4)",
            fontWeight: "600",
            zIndex: 2000,
            display: "flex",
            alignItems: "center",
            gap: "8px",
          }}
          className="animate-fade"
        >
          <span>{toast.type === "success" ? "✓" : "⚠"}</span>
          <span>{toast.message}</span>
        </div>
      )}

      {/* Top Navbar */}
      <header
        className="glass-panel"
        style={{
          padding: "20px 28px",
          marginBottom: "24px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          flexWrap: "wrap",
          gap: "16px",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "14px" }}>
          <div
            style={{
              width: "44px",
              height: "44px",
              borderRadius: "12px",
              background: "linear-gradient(135deg, #6366f1, #06b6d4)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: "1.4rem",
              boxShadow: "0 0 20px rgba(99,102,241,0.4)",
            }}
          >
            ⚡
          </div>
          <div>
            <h1 style={{ fontSize: "1.5rem", fontWeight: "800", letterSpacing: "-0.02em" }}>
              EmpFlow
            </h1>
            <p style={{ fontSize: "0.82rem", color: "var(--text-muted)", marginTop: "2px" }}>
              Supabase Powered Employee Directory
            </p>
          </div>
        </div>

        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "6px",
              padding: "6px 12px",
              background: "rgba(16, 185, 129, 0.1)",
              border: "1px solid rgba(16, 185, 129, 0.2)",
              borderRadius: "20px",
              fontSize: "0.78rem",
              color: "#6ee7b7",
              fontWeight: "600",
            }}
          >
            <span
              style={{
                width: "8px",
                height: "8px",
                borderRadius: "50%",
                background: "#10b981",
                boxShadow: "0 0 8px #10b981",
              }}
            />
            Backend Port 4000 Connected
          </div>

          <button className="btn btn-primary" onClick={handleOpenAddModal}>
            <span>+</span> Add Employee
          </button>
        </div>
      </header>

      {/* Database Error Banner with SQL Setup Helper */}
      {error && (
        <div
          className="glass-panel"
          style={{
            padding: "20px 24px",
            marginBottom: "24px",
            borderLeft: "4px solid var(--accent-rose)",
            background: "rgba(244, 63, 94, 0.08)",
          }}
        >
          <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "16px" }}>
            <div>
              <h3 style={{ color: "#fecdd3", fontSize: "1.1rem", marginBottom: "4px" }}>
                ⚠ Connection / Database Notice
              </h3>
              <p style={{ color: "var(--text-muted)", fontSize: "0.9rem", lineHeight: "1.5" }}>
                {error}
              </p>
              <p style={{ color: "var(--text-subtle)", fontSize: "0.82rem", marginTop: "6px" }}>
                If you haven't created the <code style={{ color: "#67e8f9" }}>employee</code> table in Supabase yet, click below to view the setup SQL.
              </p>
            </div>
            <button
              className="btn btn-secondary"
              style={{ fontSize: "0.82rem" }}
              onClick={() => setShowSql(!showSql)}
            >
              {showSql ? "Hide SQL" : "Show Setup SQL"}
            </button>
          </div>

          {showSql && (
            <div style={{ marginTop: "16px", background: "#050810", padding: "16px", borderRadius: "12px", border: "1px solid rgba(255,255,255,0.1)" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                <span style={{ fontSize: "0.8rem", color: "var(--text-muted)", fontWeight: "600" }}>Execute in Supabase SQL Editor:</span>
                <button
                  className="btn btn-secondary"
                  style={{ padding: "4px 10px", fontSize: "0.75rem" }}
                  onClick={() => {
                    navigator.clipboard.writeText(SQL_SCHEMA_SNIPPET);
                    alert("SQL copied to clipboard!");
                  }}
                >
                  📋 Copy SQL
                </button>
              </div>
              <pre style={{ color: "#a5b4fc", fontSize: "0.8rem", fontFamily: "JetBrains Mono, monospace", overflowX: "auto" }}>
                {SQL_SCHEMA_SNIPPET}
              </pre>
            </div>
          )}
        </div>
      )}

      {/* Metrics Row */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
          gap: "16px",
          marginBottom: "24px",
        }}
      >
        <div className="glass-panel" style={{ padding: "20px" }}>
          <div style={{ color: "var(--text-muted)", fontSize: "0.82rem", fontWeight: "600" }}>Total Employees</div>
          <div style={{ fontSize: "2rem", fontWeight: "800", marginTop: "4px", color: "#fff" }}>{totalEmployees}</div>
        </div>

        <div className="glass-panel" style={{ padding: "20px" }}>
          <div style={{ color: "var(--text-muted)", fontSize: "0.82rem", fontWeight: "600" }}>Active Departments</div>
          <div style={{ fontSize: "2rem", fontWeight: "800", marginTop: "4px", color: "var(--accent-cyan)" }}>{activeDepts}</div>
        </div>

        <div className="glass-panel" style={{ padding: "20px" }}>
          <div style={{ color: "var(--text-muted)", fontSize: "0.82rem", fontWeight: "600" }}>Total Payroll</div>
          <div style={{ fontSize: "2rem", fontWeight: "800", marginTop: "4px", color: "var(--accent-emerald)" }}>
            ${totalSalary.toLocaleString()}
          </div>
        </div>

        <div className="glass-panel" style={{ padding: "20px" }}>
          <div style={{ color: "var(--text-muted)", fontSize: "0.82rem", fontWeight: "600" }}>Average Salary</div>
          <div style={{ fontSize: "2rem", fontWeight: "800", marginTop: "4px", color: "var(--accent-amber)" }}>
            ${avgSalary.toLocaleString()}
          </div>
        </div>
      </div>

      {/* Filter and View Controls Toolbar */}
      <div
        className="glass-panel"
        style={{
          padding: "16px 20px",
          marginBottom: "24px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          flexWrap: "wrap",
          gap: "16px",
        }}
      >
        {/* Search & Dept Pills */}
        <div style={{ display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap", flex: 1 }}>
          <input
            type="text"
            className="input-field"
            placeholder="Search by name, email, role..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{ width: "260px" }}
          />

          <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
            {DEPARTMENTS.map((dept) => (
              <button
                key={dept}
                onClick={() => setSelectedDept(dept)}
                style={{
                  padding: "6px 14px",
                  borderRadius: "20px",
                  fontSize: "0.8rem",
                  fontWeight: "600",
                  border: "none",
                  cursor: "pointer",
                  transition: "all 0.2s ease",
                  background: selectedDept === dept ? "var(--primary)" : "rgba(255,255,255,0.05)",
                  color: selectedDept === dept ? "#fff" : "var(--text-muted)",
                }}
              >
                {dept}
              </button>
            ))}
          </div>
        </div>

        {/* View Toggle Buttons */}
        <div style={{ display: "flex", gap: "6px" }}>
          <button
            className={`btn-icon ${viewMode === "table" ? "btn-primary" : ""}`}
            onClick={() => setViewMode("table")}
            title="Table View"
            style={{ display: "flex", alignItems: "center", justifyContent: "center" }}
          >
            ☰
          </button>
          <button
            className={`btn-icon ${viewMode === "grid" ? "btn-primary" : ""}`}
            onClick={() => setViewMode("grid")}
            title="Grid View"
            style={{ display: "flex", alignItems: "center", justifyContent: "center" }}
          >
            ☷
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      {loading ? (
        <div className="glass-panel" style={{ padding: "40px", textAlign: "center", color: "var(--text-muted)" }}>
          Loading employee records...
        </div>
      ) : filteredEmployees.length === 0 ? (
        <div className="glass-panel" style={{ padding: "60px 20px", textAlign: "center" }}>
          <div style={{ fontSize: "2.5rem", marginBottom: "12px" }}>👤</div>
          <h3 style={{ fontSize: "1.2rem", fontWeight: "700", marginBottom: "6px" }}>No employees found</h3>
          <p style={{ color: "var(--text-muted)", fontSize: "0.9rem", marginBottom: "20px" }}>
            {employees.length === 0
              ? "Your employee directory is empty. Add your first employee to get started!"
              : "No records match your search filter."}
          </p>
          {employees.length === 0 && (
            <button className="btn btn-primary" onClick={handleOpenAddModal}>
              + Add First Employee
            </button>
          )}
        </div>
      ) : viewMode === "table" ? (
        /* Table View */
        <div className="glass-panel" style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left", fontSize: "0.9rem" }}>
            <thead>
              <tr style={{ borderBottom: "1px solid var(--border-color)", color: "var(--text-muted)", fontSize: "0.8rem", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                <th style={{ padding: "16px 20px" }}>Employee</th>
                <th style={{ padding: "16px 20px" }}>Email</th>
                <th style={{ padding: "16px 20px" }}>Department</th>
                <th style={{ padding: "16px 20px" }}>Role</th>
                <th style={{ padding: "16px 20px" }}>Salary</th>
                <th style={{ padding: "16px 20px", textAlign: "right" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredEmployees.map((emp) => (
                <tr key={emp.id} style={{ borderBottom: "1px solid rgba(255,255,255,0.04)", transition: "background 0.2s ease" }}>
                  <td style={{ padding: "14px 20px" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                      <div className="avatar">{getInitials(emp.name)}</div>
                      <div>
                        <div style={{ fontWeight: "700", color: "#fff" }}>{emp.name}</div>
                        <div style={{ fontSize: "0.78rem", color: "var(--text-subtle)" }}>@{emp.username}</div>
                      </div>
                    </div>
                  </td>
                  <td style={{ padding: "14px 20px", color: "var(--text-muted)" }}>{emp.email}</td>
                  <td style={{ padding: "14px 20px" }}>
                    <span className={`badge ${getBadgeClass(emp.department)}`}>{emp.department}</span>
                  </td>
                  <td style={{ padding: "14px 20px", color: "var(--text-main)", fontWeight: "500" }}>{emp.role}</td>
                  <td style={{ padding: "14px 20px", fontWeight: "700", color: "var(--accent-emerald)" }}>
                    ${Number(emp.salary || 0).toLocaleString()}
                  </td>
                  <td style={{ padding: "14px 20px", textAlign: "right" }}>
                    <div style={{ display: "flex", justifyContent: "flex-end", gap: "8px" }}>
                      <button className="btn-icon" title="Edit" onClick={() => handleOpenEditModal(emp)}>
                        ✎
                      </button>
                      <button className="btn-icon" title="Delete" style={{ color: "#f87171" }} onClick={() => setDeleteTarget(emp)}>
                        ✕
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        /* Grid View */
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "20px" }}>
          {filteredEmployees.map((emp) => (
            <div key={emp.id} className="glass-panel" style={{ padding: "24px", display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
              <div>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "16px" }}>
                  <div className="avatar" style={{ width: "48px", height: "48px", fontSize: "1.1rem" }}>
                    {getInitials(emp.name)}
                  </div>
                  <span className={`badge ${getBadgeClass(emp.department)}`}>{emp.department}</span>
                </div>

                <h3 style={{ fontSize: "1.1rem", fontWeight: "700", marginBottom: "2px" }}>{emp.name}</h3>
                <p style={{ fontSize: "0.8rem", color: "var(--text-subtle)", marginBottom: "12px" }}>@{emp.username}</p>

                <div style={{ fontSize: "0.85rem", color: "var(--text-muted)", display: "flex", flexDirection: "column", gap: "6px" }}>
                  <div>💼 <strong>Role:</strong> {emp.role}</div>
                  <div>✉️ <strong>Email:</strong> {emp.email}</div>
                  <div>💵 <strong>Salary:</strong> <span style={{ color: "var(--accent-emerald)", fontWeight: "700" }}>${Number(emp.salary || 0).toLocaleString()}</span></div>
                </div>
              </div>

              <div style={{ display: "flex", gap: "10px", marginTop: "20px", paddingTop: "14px", borderTop: "1px solid var(--border-color)" }}>
                <button className="btn btn-secondary" style={{ flex: 1, padding: "6px" }} onClick={() => handleOpenEditModal(emp)}>
                  Edit
                </button>
                <button className="btn btn-danger" style={{ padding: "6px 12px" }} onClick={() => setDeleteTarget(emp)}>
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create / Edit Employee Modal */}
      {isModalOpen && (
        <div className="modal-overlay" onClick={() => setIsModalOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <h2 style={{ fontSize: "1.3rem", fontWeight: "700" }}>
                {editingEmployee ? "Edit Employee" : "Add New Employee"}
              </h2>
              <button className="btn-icon" onClick={() => setIsModalOpen(false)}>✕</button>
            </div>

            <form onSubmit={handleSaveEmployee}>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                <div className="form-group">
                  <label>Full Name *</label>
                  <input
                    type="text"
                    required
                    className="input-field"
                    placeholder="e.g. Alex Smith"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  />
                </div>

                <div className="form-group">
                  <label>Username *</label>
                  <input
                    type="text"
                    required
                    className="input-field"
                    placeholder="e.g. alexs"
                    value={formData.username}
                    onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                  />
                </div>
              </div>

              <div className="form-group">
                <label>Email Address *</label>
                <input
                  type="email"
                  required
                  className="input-field"
                  placeholder="e.g. alex@company.com"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                />
              </div>

              <div className="form-group">
                <label>Password *</label>
                <input
                  type="text"
                  required
                  className="input-field"
                  placeholder="Employee password"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                />
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                <div className="form-group">
                  <label>Department *</label>
                  <select
                    className="input-field"
                    style={{ background: "#1f2937", color: "#fff" }}
                    value={formData.department}
                    onChange={(e) => setFormData({ ...formData, department: e.target.value })}
                  >
                    <option value="Engineering">Engineering</option>
                    <option value="Product">Product</option>
                    <option value="Sales">Sales</option>
                    <option value="Design">Design</option>
                    <option value="HR">HR</option>
                  </select>
                </div>

                <div className="form-group">
                  <label>Role / Position *</label>
                  <input
                    type="text"
                    required
                    className="input-field"
                    placeholder="e.g. Developer"
                    value={formData.role}
                    onChange={(e) => setFormData({ ...formData, role: e.target.value })}
                  />
                </div>
              </div>

              <div className="form-group">
                <label>Annual Salary ($) *</label>
                <input
                  type="number"
                  required
                  min="0"
                  className="input-field"
                  placeholder="e.g. 75000"
                  value={formData.salary}
                  onChange={(e) => setFormData({ ...formData, salary: e.target.value })}
                />
              </div>

              <div style={{ display: "flex", justifyContent: "flex-end", gap: "12px", marginTop: "24px" }}>
                <button type="button" className="btn btn-secondary" onClick={() => setIsModalOpen(false)}>
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary">
                  {editingEmployee ? "Save Changes" : "Create Employee"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteTarget && (
        <div className="modal-overlay" onClick={() => setDeleteTarget(null)}>
          <div className="modal-content" style={{ maxWidth: "440px" }} onClick={(e) => e.stopPropagation()}>
            <h3 style={{ fontSize: "1.2rem", fontWeight: "700", color: "#f87171", marginBottom: "8px" }}>
              Delete Employee Record?
            </h3>
            <p style={{ color: "var(--text-muted)", fontSize: "0.9rem", lineHeight: "1.5", marginBottom: "20px" }}>
              Are you sure you want to delete <strong>{deleteTarget.name}</strong> (@{deleteTarget.username})? This action cannot be undone.
            </p>
            <div style={{ display: "flex", justifyContent: "flex-end", gap: "12px" }}>
              <button className="btn btn-secondary" onClick={() => setDeleteTarget(null)}>
                Cancel
              </button>
              <button className="btn btn-danger" onClick={handleDeleteEmployee}>
                Confirm Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Employees;
